recipes/gnuradio.lwr
We don't require it and it causes installs of other dependencies not needed.
=> recipes: gnuradio: remove ICE as a dependency

recipes/mcpp.lwr
The current recipe points to a URL that no longer seems to be responding. This patch updates to use sourceforge, which I think should be more stable.
=> recipes: mcpp: changed download location to use sourceforge

recipes/gr-pocsag.lwr
It seems cgran.org experienced some issues and is starting from scratch. The repository location has changed.
=> Fixed SVN Repository URL for gr-pocsag recipe.

mod_pybombs/pybombs_ops.py, pybombs
Two print statements, which are possible for quick debug purposes, are left. It gives "False" and "value updated" output when running. They are removed in this commit.
=> remove two debug print statements

templates/cmake.lwt
If you add a bit of debug print to the template you see this change
Before:
echo I am the cmake template - my config opt is ""
CC=gcc CXX=g++ cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/home/gnuradio
After
echo I am the cmake template - my config opt is " -DINSTALL_UDEV_RULES=OFF"
CC=gcc CXX=g++ cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/home/gnuradio  -DINSTALL_UDEV_RULES=OFF
=> don't wipe out the user's chosen config_opt

app_store.py, mod_pybombs/pybombs_ops.py, mod_pybombs/recipe.py
This allows recipes to have a new "description:" property, which I need to make pybombs display a brief synopsis of each module/recipe.
Needed for gnuradio/recipes#31
=> add a handler for "description:"

src-reference.sh
Thanks to @jmcorgan for the cluebat. Fixes gnuradio/pybombs#174
I added a reference to the pybombs wiki linking this PR, and will update when this is closed.
=> Add a tool to create a git reference directory

mod_pybombs/pybombs_ops.py
Example output:
gnuradio    installed  inventory 55d8f482f5acf33b8f629556a4fa5019908bb4be git://http://www.gnuradio.org/git/gnuradio.git
gr-acars                    None
gr-acars2    installed  inventory adcc989e5b44633326a52d504b51bb735f371ae1 git://https://github.com/antoinet/gr-acars2.git
GNU Radio processing block for ACARS transmissions
gr-adsb                    None
GNU Radio ADSB decoder and framer
gr-air-modes                    None
Gnuradio Mode-S/ADS-B decoder
=> add recipe description to output of "pybombs list"

mod_pybombs/fetch.py
.xz compression (which is pretty common) is not supported by pybombs. 
I refactored the extract method to deduplicate cloned code and to handle 3 kinds of compression compatible with tar.
I also fixed a formatting bug when the filetype wasn't known.
=> Enable .tar.xz files to be extracted in pybombs

src-reference.sh
This prevents all these other projects from cluttering up the pybombs directory
=> make the reference directory its own repo

pybombs/packagers/yum.py
Some packages have an 'epoch number' that is not parsed correctly, for example PyBOMBS sees the version number as '1' for qt-devel on Fedora 23:
$ dnf list qt-devel
qt-devel.x86_64 1:4.8.7-5.fc23 @updates
This patch modifies the regex to ignore the epoch. Not an issue for 'dnf info', which puts the epoch on a separate line.
=> Ignore epoch in DNF version numbers.

pybombs/commands/install.py
Crash when accessing deps_only in update handler. The option is only defined in the install handler. Handlers for install and update are implemented by the same code, so add a check.
=> Do not access 'deps_only' in 'update' handler

pybombs/config_file.py
eg:
$ env PYTHONPATH=. python pybombs/main.py recipes list
Error loading /home/ckuethe/.pybombs/config.yml: while scanning for the next token
found character '\t' that cannot start any token
in "<string>", line 23, column 1:
forcebuild: True
=> emit useful output when config file is invalid

pybombs/recipes/autoconf.lwr, pybombs/recipes/automake.lwr, pybombs/recipes/python.lwr
Added port packager for the three moved recipes (automake, autoconf, python). This packager is already merged here, so all the recipes in this repo should support it.
=> Modified moved recipes for packager port

pybombs/fetcher.py
The original pybombs allowed config vars to be used in the source line of recipes. This commit is intended to add this functionality.
For example, suppose I wanted to create a source line with a standard SSH locator:
```
source: git+<username>@<somemachine>:<reponame>.git
```
However, I don't really want my recipe to contain `<username>`. So I update my recipe to contain:
```
source: git+$somemachineusername@<somemachine>:<reponame>.git
```
Now, anyone who has an account on `<somemachine>` can use my recipe and they shouldn't be using my recipe if they don't.
This pull should fix #343.
=> Allow config vars to be used in the source line of recipes.

pybombs/fetchers/git.py
Commit https://github.com/gnuradio/pybombs/commit/e756d7f2a3b3f3c6f433561c77680b7e2bed74d7 fails to parse a location of the form:
```
pybombs recipes add <alias> git+<username>@<IP|HOSTNAME>:<path/to/repo.git>@<commit|rev|tag>
```
Please reopen #358
My regex foo isn't great, but this commit handles both (normal and SSH) cases.
=> Handle ssh location when using git.

pybombs/packagers/portage.py
Installation works now without shell=True and with correct arguments.
Thanks @skoslowski, @mbr0wn for pointing me to the right direction!
=> Fix packager portage

pybombs/packagers/pacman.py
If looking for installed packages currently -Si parameter is used. But this only lists available packages for installation.
=> packagers: pacman: change -Si to -Qi

pybombs/commands/fetch.py
Check if the current recipe has a 'source' attribute set, before accessing it to test its length to establish it the source string is a nonempty URL.
This way, recipes which do not have a source field set issue a warning message, but do not raise an AttributeError exception, stopping the fetch for other packages:
Traceback (most recent call last):
File "/usr/local/bin/pybombs", line 11, in <module>
load_entry_point('PyBOMBS==2.1.1a0', 'console_scripts', 'pybombs')()
File "/usr/local/lib/python2.7/dist-packages/pybombs/main.py", line 32, in main
return dispatch() or 0
File "/usr/local/lib/python2.7/dist-packages/pybombs/commands/base.py", line 188, in dispatch
return get_cmd_dict(cmd_list)[args.command](cmd=args.command, args=args).run()
File …
=> fetch.py: check if the attribute 'sources' is defined for the recipe before testing for its length

pybombs/recipe.py
allows 'pybombs lint db48.lwr' to not crash, as discovered at grcon16
=> fix string formatter

pybombs/recipes/build-essential.lwr
Revealed by new apt show error.
=> Fixed package name of build-essential, not build_essential.

pybombs/packagers/apt.py, pybombs/utils/utils.py
Affects get_available_version() and get_installed_version() when python-apt is installed. Gracefully falls back to old approach otherwise. Displays a warning if python-apt is not installed.
Approximately 6.7x speedup of "pybombs recipes list" on my machine.
Note that I am unable to test on a machine that does not have Apt, so I'm not sure whether this gracefully handles that situation. Unsure if the warning will be displayed on non-Apt machines.
The unusual "python_apt_import" step is required because apt.py in this package conflicts with python-apt.
=> Implemented python-apt support for caching

README.md, pybombs/config_manager.py, pybombs/dep_manager.py, pybombs/install_manager.py, pybombs/package_manager.py, pybombs/packagers/source.py, pybombs/requirer.py, run-tests.sh, tests/run_docker_tests.sh
Following this commit, satisfy_order is ignored. PyBOMBS will now
always first install packages from binary sources unless told otherwise,
and then install all the source packages.
=> Replace the satisfy_order option with a stricter install procedure

pybombs/packagers/zypper.py, tests/docker/opensuse_tw/Dockerfile
I added a Dockerfile that passes its build test and references the latest commit to the master branch of jaredd/gr-recipes which fixes a couple recipes.  Any commit to gnuradio/pybombs will require a change to the pybombs recipes on line 21, but should correspond to an update to gr-recipes from my master branch.
=> Packagers new zypper: Dockerfile

README.md, setup.py
url http://gnuradio.org/pybombs shows "Page not found".
Use https://www.gnuradio.org/blog/pybombs-the-what-the-how-and-the-why/ instead.
Signed-off-by: Fumihiko Kakuma <kakuma@valinux.co.jp>
=> Fix invalid url link

README.md
Documenting the fact that `gitbranch` accepts git tags, not only branches.
=> docs: tags can be used in gitbranch (not only branches)

pybombs/package_manager.py, pybombs/packagers/__init__.py, pybombs/packagers/source.py
For the case where there's no prefix, we might still need someone who
speaks for source-only recipes.
This fixes the bug where users try and run 'pybombs recipes list'
without having a prefix.
=> Added NoSource fake package manager

pybombs/gitcache_manager.py
Allows use of git pre-2.7 in addition to latest versions
Fixes #473
=> gitcache_manager: Use git config to fetch remote url

pybombs/recipes/python.lwr
Fedora 26 provides only python2-devel and python3-devel packages
=> recipes: Added python2-devel to Fedora package list

pybombs/utils/archives.py
ZipFile doesn't have a getnames(), so opening zip file archives always failed. Replace that with the appropriate method for zips.
=> Fix support for zip files

pybombs/commands/install.py
As it stands, `pybombs install ...` will always return a sucessful error code, even if it fails, which breaks assumptions about how any program is run. This simply passes back an appropriate error code
=> Return a failing exit code if install fails

pybombs/recipe.py, pybombs/utils/utils.py
ruamel.yaml recently changed from subclassing ``dict`` and ``list`` for resp. ``CommentedMap`` and ``CommentedList``. 
At two places ``ininstance`` checks were made against ``dict`` and ``list`` that no did see the YAML loaded data as such. Since ``list`` is registered as a ``MutableSequence`` and ``dict`` as a ``MutableMapping`` it is much more appropriate to test against those, or even to there parents (if you only read from the first parameter to ``isinstance`` anyway).
AFAIK ``six`` doesn't give you these abstract base classes, hence the ``try`` (failing on Python < 3).
=> fixes issue #517 pybombs assumed dict and list instances

pybombs/config_manager.py
We were having an issue where people weren't seeing anything in the documentation tab of a block in GRC, and it turns out it's because this was disabled by default.  Yes I know you can enable doxygen with a flag, but so many people are using pybombs with the standard "pybombs install gnuradio" as their go-to method for new installs, and it makes GR seem less mature when the documentation tabs are empty.
Let me know if it makes more sense to change gnuradio.lwr instead of this.
=> build doxygen set to true by default

pybombs/config_file.py
Travis CI began failing in 4cbdab04741e0735f0db697fd9a79a3ee1c0089e due to the following pylint error:
```
************* Module pybombs.config_file
E: 62,19: Unexpected keyword argument 'default_flow_style' in method call (unexpected-keyword-arg)
```
It seems pylint is confused because `AbstractYaml.__init__` may leave `_dump` uninitialized. In any case, 4cbdab04741e0735f0db697fd9a79a3ee1c0089e made it impossible to reach the problematic `else` clause in `AbstractYaml.dump`, so we can simply remove the whole `if` statement.
I also noticed that ruamel version check was broken; it requires the minor version number to be at least 15, and so it would incorrectly reject things like versions 1.0 through 1.14 (if they were to appear in the future). I simplified the check to compare against the …
=> Fix broken CI

pybombs/config_manager.py
When I build GNU Radio 3.8 with PyBOMBS on Ubuntu 20.04, most of the Python modules end up in `prefix/lib/python3/*`. But PyBOMBS only adds `prefix/lib/python3.8/*` to the `PYTHONPATH` in `setup_env.sh`. To fix this, I've extended the `conservative_guess` list to include both `pythonX` and `pythonX.Y`.
=> Include both pythonX and pythonX.Y in PYTHONPATH

tests/docker/ubuntu_2004/Dockerfile
Here is a minimal docker build using Ubuntu 20.04.
It is derived from the [ubuntu_1804_py3k image](https://github.com/gnuradio/pybombs/blob/master/tests/docker/ubuntu_1804_py3k/Dockerfile), i.e., it uses Python 3 by default.
Builds fine for me, but only after adding an `apt-get install -qq -y pkg-config` line. Otherwise, installation of gr-osmosdr fails during the installation of airspy. Not sure if this should be upstreamed into the airspy.lwr as a dependency? Some context:
* just installing `pybombs install airspy` on a fresh Ubuntu 18.04 will fail with the same issue, however installing `pybombs install gr-osmosdr` works fine (probably because pkg-config gets installed somewhere during the tree installation before airspy gets installed
* Not sure how deterministic tree resolution is, …
=> Dockerfile for testing Ubuntu 20.04

.travis.yml
We may as well test PyBOMBS against Python 3.7 and 3.8. I've done that here, and will merge if Travis is happy.
=> travis: add newer Python versions

pybombs/utils/subproc.py
Under Python3, when I tried the command
`pybombs recipes add-defaults`
I got an error raised in <python3-dir>/pybombs/utils/subproc.py:
```
File "/usr/local/lib/python3.9/site-packages/pybombs/utils/subproc.py", line 243, in monitor_process
while monitor_thread.isAlive:
AttributeError: 'Thread' object has no attribute 'isAlive'
```
The simple fix was to change the method called isAlive to is_alive, as that was changed in python3.  The command to add the default recipes worked after this fix.
=> In utils/subproc.py: Change threading.Thread monitor_thread method isAlive to is_alive

setup.cfg
This addresses the following warning identified in CI:
> UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
=> Fix deprecation warning
